### ISSUE TITLE
Cameras gLTF model does not display properly

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#27]
I tried to display the sample below but it was not displayed properly.
Model : Cameras
https://github.com/cx20/gltf-test/tree/2.0/tutorialModels/Cameras
![image](https://raw.githubusercontent.com/cx20/gltf-test/2.0/tutorialModels/Cameras/screenshot/screenshot.png)

Result : [Cameras model result](https://cdn.rawgit.com/cx20/gltf-test/4a4400f2babf4e481de25a8bb2a09020d939db4a/examples/grimoiregl/index.html?category=tutorialModels&model=Cameras&scale=1&type=glTF)
![image](https://cloud.githubusercontent.com/assets/1833979/26286101/cec98104-3e97-11e7-81f9-b570e6a08248.png)

**Comment by cx20** [comment]
I think this model needs to specify gl.TRIANGLES instead of gl.TRIANGLE_STRIP as the primitive type.
Since there is no specification of the primitive type in this model, it is necessary to use the default value.
See: https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#primitive

**Comment by cx20** [comment]
Tracing with Spector.js, the primitive type of this sample was already TRIANGLES.

**Comment by kyasbal-1994** [comment]
This might be fixed with grimoirejs-gltf@0.0.9-development
