### ISSUE TITLE
Have memory leaks occurred when loading glTF 2.0 version of Buggy.gltf?

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#28]
[Grimoire.js + glTF 1.0 Result](https://cx20.github.io/gltf-test/examples/grimoiregl/index.html?model=Buggy&scale=0.02):
![image](https://cloud.githubusercontent.com/assets/1833979/26314841/2b71e3e4-3f4a-11e7-8f5a-992b7acb693c.png)
[Grimoire.js + glTF 2.0 Result](https://cdn.rawgit.com/cx20/gltf-test/4a4400f2babf4e481de25a8bb2a09020d939db4a/examples/grimoiregl/index.html?model=Buggy&scale=0.02) :
![image](https://cloud.githubusercontent.com/assets/1833979/26314845/30f4d6fa-3f4a-11e7-9ade-8f773585a140.png)

**Comment by cx20** [comment]
[NG] Windows 10 + Chrome 58.0.3029.110
[NG] Windows 10 + Firefox 53.0
[OK] Mac OS X10.12 + Chrome 58.0.3029.110 (displayed but heavy)
[OK] Mac OS X10.12 + Firefox 49.0 (displayed but heavy)

**Comment by kyasbal-1994** [comment]
I couldn't reproduce this problem even with Windows10.

![](https://gyazo.com/61b2152c90825915f45dbd93e09ad23c)

**Comment by cx20** [comment]
This problem was due to WebGL Inspector.
![image](https://user-images.githubusercontent.com/1833979/30486557-e526e61e-9a6b-11e7-8655-7efe2581451b.png)
When it was invalidated, memory consumption was reduced.

before
![image](https://user-images.githubusercontent.com/1833979/30486630-17de9e62-9a6c-11e7-8b74-8c8909fb9d62.png)

after
![image](https://user-images.githubusercontent.com/1833979/30486647-29426ac6-9a6c-11e7-82fc-26b1eeb9b135.png)
