### ISSUE TITLE
Grimoire.js + glTF Loader does not support glTF 1.1.

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#3]
I tried the glTF 1.1 sample with some glTF Loader.
https://github.com/cx20/gltf-test#gltf-11-tutorial-models
https://cx20.github.io/gltf-test/

Related: https://github.com/javagl/JglTF/issues/10#issuecomment-269810809

I would like each library to be all green.

**Comment by kyasbal-1994** [comment]
Should we support glTF 1.1 yet?

**Comment by cx20** [comment]
glTF 1.1 has been renamed to 2.0.
Since there is no model of glTF1.1 also in the following repository, support of glTF1.1 is unnecessary.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0
