### ISSUE TITLE
Skinning animation for glTF 2.0 is incorrect

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#40]
I tried the latest version of Grimoire.js and glTF Plugin.
However, Skinning animation seems not to be displayed correctly.

Plugins:

|Plugin name|Version|
|:-------------|:-----:|
|grimoirejs-animation|1.1.1|
| rimoirejs-gltf|2.1.2|

[Grimoire.js + glTF/RiggedFigure.gltf Result:](https://cdn.rawgit.com/cx20/gltf-test/2b68a75f44410d79a36762d91ccfa39cbcafdec6/examples/grimoiregl/index.html?model=RiggedFigure&scale=1)
![gltf_20170610_001](https://user-images.githubusercontent.com/1833979/27034130-3a2b181a-4fb7-11e7-9d60-bc457850a9fa.gif)

[Grimoire.js + glTF/AnimatedTriangle.gltf Result:](https://cdn.rawgit.com/cx20/gltf-test/2b68a75f44410d79a36762d91ccfa39cbcafdec6/examples/grimoiregl/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
![gltf_20170610_003 gif](https://user-images.githubusercontent.com/1833979/27034174-642beb8a-4fb7-11e7-97bc-df9cfaf465c1.gif)

**Comment by cx20** [comment]
I confirmed that the following trouble has been fixed.
- [x] The head of RiggedFigure.gltf is twisted
- [x] The motion of AnimatedTriangle.gltf is not smooth

However, RiggedFigure.gltf still seems to be lying down.

I do not know if it is related, but COLLADA data of the lying model seems to be up_axis as Z_UP.
![image](https://user-images.githubusercontent.com/1833979/27508711-fe4fba94-5925-11e7-9856-321d0a4568cb.png)

**Comment by cx20** [comment]
Related : http://docs.garagegames.com/torque-3d/official/content/documentation/Artist%20Guide/Formats/ColladaLoader.html
![image](https://user-images.githubusercontent.com/1833979/27508926-6b9e64ec-592b-11e7-8d8c-c88376bcbc3c.png)

**Comment by cx20** [comment]
I think Grimoire.js that the model is displayed lying down it because the matrix for correcting Z_UP is not loaded.

I tried editing the following matrix of RiggedSimple.gltf. In Three.js, I confirmed that the model is displayed lying down.
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/RiggedSimple/glTF/RiggedSimple.gltf#L20-L37
```
    "matrix": [
        1.0, 0.0, 0.0, 0.0,
        0.0, 0.0,-1.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0
    ]
```
![image](https://user-images.githubusercontent.com/1833979/27511897-742a0e00-596b-11e7-87cd-626f01712422.png)

```
    "matrix": [
        1.0, 0.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 1.0
    ]
```
![image](https://user-images.githubusercontent.com/1833979/27511905-a4f1d2ca-596b-11e7-8491-b9fda6411033.png)

**Comment by cx20** [comment]
I think that the applyMatrix or getRotation function is doubtful.
[TransformComponent#applyMatrix function](https://github.com/GrimoireGL/grimoirejs-fundamental/blob/master/src/Components/TransformComponent.ts#L203-L210)
[Matrix#getRotatoin function](https://github.com/GrimoireGL/grimoirejs-math/blob/master/src/Matrix.ts#L409-L414)

**Comment by kyasbal-1994** [comment]
This problem cant be proved with mis-implementation of applyMatrix or getRotation since these methods are often used in VC model also.
As far as my inspection, this problem only occur on skinned models.

**Comment by cx20** [comment]
I confirmed that Issue lying down has been resolved.
https://github.com/GrimoireGL/grimoirejs-fundamental/pull/100

[Grimoire.js + glTF/RiggedFigure.gltf Result:](https://cdn.rawgit.com/cx20/gltf-test/7b45c616ddd106a1c0f57c932920438e7cdfbd1f/examples/grimoiregl/index.html?model=RiggedFigure&scale=1)
![image](https://user-images.githubusercontent.com/1833979/27515503-6bcb2a2c-59df-11e7-914d-5252c0c4e71f.png)
