### ISSUE TITLE
Description of the package is blank

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#6]
https://www.npmjs.com/~grimoire.gl

![image](https://cloud.githubusercontent.com/assets/1833979/21952899/fdd8f636-da6b-11e6-94d3-bbeb7c1c61b0.png)

I think you probably need to add a description to package.json.
https://github.com/GrimoireGL/grimoirejs-gltf/blob/master/package.json#L4

**Comment by kyasbal-1994** [comment]
Merged with https://github.com/GrimoireGL/grimoirejs-gltf/pull/7
