### ISSUE TITLE
Corset.gltf looks whitish

### ISSUE THREAD

**Issue by cx20** [GrimoireGL/grimoirejs-gltf#70]
The following is a comparison of display results in each library.
https://github.com/cx20/gltf-test#pbr-models
![image](https://user-images.githubusercontent.com/1833979/30337319-de6ee3a8-9822-11e7-9bae-91983bac7840.png)
In Grimoire.js, Corset.gltf looks whitish.

Below is the display result when GLSL gamma correction is commented out.
![image](https://user-images.githubusercontent.com/1833979/30337422-33d15a06-9823-11e7-905b-659771bfebd1.png)

```glsl
  //gl_FragColor.rgb = pow(gl_FragColor.rgb,1.0/vec3(2.2));
```

Probably gamma correction is unnecessary.

**Comment by kyasbal-1994** [comment]
Solved with latest release
